CREATE TABLE PRODUCT (ID INT AUTO_INCREMENT PRIMARY KEY, PRODUCT VARCHAR(45));
INSERT INTO PRODUCT (ID, PRODUCT) VALUES (1, 'test');

CREATE TABLE USER_ENTITY (ID INT AUTO_INCREMENT PRIMARY KEY, user_name VARCHAR(45), user_role VARCHAR(20) );
INSERT INTO USER_ENTITY (ID, user_name, user_role) VALUES (1, 'admin', 'USER');